kind: pipeline
type: docker
name: default

steps:
- name: 1
  image: busybox
  commands:
  - echo "1"
  - sh /fakesh_to_produce_error.sh
---
kind: pipeline
type: docker
name: second

steps:
- name: 2
  image: busybox
  commands:
  - echo "2"

depends_on:
- default
